import Profile from "@/components/Profile/Profile";
import { Metadata } from "next";
import { getServerMe } from "@/lib/api/serverApi";

export const metadata: Metadata = {
  title: "Your profile",
  description: "Generated by create next app",
  openGraph: {
    title: "Note hub",
    description: "Generated by create next app",
    url: `https://notehub.com`,
    images: [
      {
        url: "https://ac.goit.global/fullstack/react/notehub-og-meta.jpg",
        alt: "Note hub",
        width: 1200,
        height: 630,
      },
    ],
  },
};

export default async function ProfilePage() {
  const { email, username, avatar } = await getServerMe();
  return <Profile email={email} username={username} src={avatar} />;
}
